name: Setup

inputs:
  shell:
    required: false
    default: ci

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v26

    - name: Embed Nix shell
      uses: nicknovitski/nix-develop@v1
      with:
        arguments: .#${{ inputs.shell }}

    - name: Cache pnpm
      uses: actions/setup-node@v4
      with:
        cache: pnpm

    - name: Install pnpm dependencies
      shell: bash
      run: pnpm install
