name: Check

on: [push, pull_request]

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm typecheck

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm lint

  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm fmt --check

  test-nodejs:
    name: Test (Node.js)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shell: [latest, lts]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          shell: nodejs-${{ matrix.shell }}
      - run: pnpm test

  test:
    name: Test (Bun)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          shell: bun-latest
      - run: bun test --coverage ./test/*

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm docs-ci
